[#50] Disallow "./github fix" when there are staged changes

diff --git a/github b/github
--- a/github
+++ b/github
@@ -9,6 +9,15 @@ if [ $CMD = "fix" ]; then
 		exit 1
 	fi
 	
+	# do not allow this if there is staged changes
+	git diff --exit-code --quiet
+	rc=$?
+	if [[ $rc != 0 ]] ; then \
+		echo "ERROR: You have unstaged changes:"; \
+		git diff; \
+		exit $rc; \
+	fi
+	
 	# make sure we are synced up with master
 	git merge master
 	rc=$?
